#+title: Champollion 2016 cont.
#+author: Patrick D. Elliott
#+bibliography: ../../bibliography/master.bib
#+setupfile: ./handout-template.org
#+OPTIONS: ':t
#+cite_export: biblatex

* Recap Exercises 

** Backround on collective conjunction of individuals

[cite:@Winter2001] develops an account of /collective conjunction of individuals/ based on the idea that the core semantic contribution of /and/ is boolean conjunction.

#+name: coll-conj
#+begin_exe
\ex John, Mary, and Sue gathered in the hallway.
#+end_exe

Winter's account made use of four essential ingredients; generalized boolean conjunction is the meaning of /and/, whereas the other three ingredients are "type shifters".

- Montague lift.
- (Generalized) boolean conjunction (i.e., set intersection).
- Minimization.
- Existential raising.
  
Step-by-step, the story is as follows:

1. Apply /Montague/ lift to the type \(E\) coordinands (result: \((E \to T) \to T\)). 
2. Conjoin the resulting expressions using generalized boolean conjunction (result: \((E \to T) \to T\)).
3. Apply minimization to the result (result: \((E \to T) \to T\)).
4. Apply existential raising to create a quantifier over pluralities (result: \(((E \to T) \to T) \to T\)).
5. Apply the resulting quantifier to the collective predicate.
   
** Exercise 1

Let's compute the meaning of "John, Mary and Sue gathered", in terms of /sets/.

I'll provide you with the meaning of each atomic expressions:

- \(\eval*{\mathbf{John}}, \eval*{\mathbf{Mary}}, \eval*{\mathbf{Sue}} = j, m, s \)
- \(\eval*{\mathbf{gathered}} = \set{ x \in \mathbf{Dom}_E | x\text{ gathered} }\)
- \(\eval*{\mathbf{and}(P_{ET})(Q_{ET})} = \set{x \in \mathbf{Dom}_E | x \in \eval*{P}\text{ and }x \in \eval*{Q}}\)  

In addition, we'll need to make use of the following type-shifters:  

- \(\eval*{\mathbf{LIFT}(x_E)} = \set{P \subseteq \mathbf{Dom}_E | x\in  P}\)
- \(\eval*{\mathbf{MIN}(Q_{(\sigma \rightarrow T) \to T})} = \set{P \in \eval*{Q} | \forall P'[P' \subset P \rightarrow \neg(P' \in \eval*{Q})]}\)
- \(\eval*{\mathbf{ER}(P)} = \set{Q \subseteq \mathbf{Dom}_E | Q \cap \eval*{P} \neq \emptyset }\)
  
You may assume the following structure for our collective coordination example.

#+begin_export latex
\begin{exe}
  \ex
  \begin{forest}
    [{\(T\)}
    [{\(((E \to T) \to T) \to T\)}
      [{???}]  
      [{\((E \to T) \to T\)}
        [{???}]
        [{\((E \to T) \to T\)}
        [{\((E \to T) \to T\)}
          [{???}]
          [{John: \(E\)}]
        ]
        [{\ldots}
          [{and: ?}]
          [{?}
          [{\((E \to T) \to T\)}
            [{???}]
            [{Mary: \(E\)}]
          ]
          [{\ldots}
            [{and: ?}]
            [{\((E \to T) \to T\)}
              [{???}]
              [{Sue: \(E\)}]
            ]
          ]
          ]
        ]
        ]
      ]
    ]
      [{gathered: \((E \to T) \to T\)}]
    ]
  \end{forest}
\end{exe}
#+end_export

- Fill in the missing type-shifters.
- Fill in the missing type-signatures, and verify that the structure is well-typed.
- Give the interpretation (as a set) for every non-atomic node (except for those labelled "\ldots").
- What are the truth-conditions for the sentence?
  
Now, provide a concrete /model/ at which:
1. The sentence is true (explain why).
2. The sentence is false (explain why).
This involves specifying a concrete domain of individuals and an extension for the lexical constants.

** Background on collective conjunction of predicates

[cite:@Champollion2016] builds on [cite:@Winter2001], by developing an account of collective conjunction of predicates, as in the following: 

#+name: disagree
#+begin_exe
\ex Every *linguist and philosopher* who disagreed with each other walked in together.
#+end_exe

- (Generalized) boolean conjunction (i.e., set intersection).
- Minimization. 
- Existential raising.
  
Step-by-step, the story is as follows:

- In order to avoid immediately deriving an intersective reading, the coordinated predicates are /existentially raised/ (result: \((E \to T) \to T\)).
- The resulting raised predicates are intersected via generalized boolean conjunction. (result: \((E \to T) \to T\))
- The resulting quantifier is /minimized/, in order to derive a predicate of collective individuals (result: \((E \to T) \to T\)). 
- The resulting predicate composes as the restrictor of a more type-general determiner.

** Exercise 2  

We'll go through the following example:

#+name: an-ill
#+begin_exe
\ex An ill-matched linguist and philosopher gave a talk together.
#+end_exe

We'll go through the composition of ([[an-ill]]) in terms of sets. A couple of important assumptions:

- We'll treat "ill-matched" as a modifier of collective individuals, that is only true of /pairs/ (type \(((E \to T) \to T) \to (E \to T) \to T\)).
- We'll treat "gave a talk together" as a predicate of collective individuals (type \((E \to T) \to T\)).
  
Here's the interpretation of the constants in terms of sets:

- \(\eval*{\mathbf{illMatched}(Q_{(ET \to T)})} = \set{P \in Q | P = \set{x,y}\text{ and }x\text{ doesn't match }y}\)
- \(\eval*{\mathbf{linguist}}  = \set{x \in \mathbf{Dom}_E | x\text{ is a linguist} }\)
- \(\eval*{\mathbf{philosopher}}  = \set{x \in \mathbf{Dom}_E | x\text{ is a philosopher} }\)
- \(\eval*{\mathbf{gaveTalkTogether}} = \set{P \subseteq \mathbf{Dom}_E | P = \set{x,y}\text{ and }x\text{ gave a talk with }y}\)
  
We'll also need a collective counterpart of the indefinite determiner /a/:

- \(\eval*{\mathbf{a}(Q_{ET \to T})} = \set{Q' \subseteq \mathbf{Dom}_E | Q \cap Q' \neq \emptyset }\)
  
Here's the structure you can assume for our example sentence:

#+begin_export latex
\begin{exe}
  \ex
  \begin{forest}
    [{?}
    [{?}
      [{a: ?}]
      [{\((E \to T) \to T\)}
        [{ill-matched: \((ET \to T) \to ET \to T\)}]
        [{\((E \to T) \to T\)}
          [{???}]
          [{\((E \to T) \to T\)}
          [{\((E \to T) \to T\)}
            [{???}]
            [{linguist: \(E \to T\)}]
          ]
          [{\ldots}
            [{and: ?}]
            [{\((E \to T) \to T\)}
              [{???}]
              [{philosopher: \(E \to T\)}]
            ]
          ]
          ]
        ]
      ]
    ]
      [{\((E \to T) \to T\)} [{gave a talk together},roof]]
    ]\end{forest}
\end{exe}
#+end_export

- Fill in the missing type-shifters.
- Fill in the missing type-signatures, and verify that the structure is well-typed.
- Give the interpretation (as a set) for every non-atomic node (except for those labelled "\ldots").
- What are the truth-conditions for the sentence?
  
Now, provide a concrete /model/ at which:
1. The sentence is true (explain why).
2. The sentence is false (explain why).
This involves specifying a concrete domain of individuals and an extension for the lexical constants.


* Justifying existential raising

- \(\eval*{\mathbf{ER}(P)} = \set{Q \subseteq \mathbf{Dom}_E | Q \cap \eval*{P} \neq \emptyset }\)
  
Existential raising is a silent operator that lifts its restrictor into an existential quantifier.

Evidence that this should be available as a silent type-shifter comes from /bare plurals/.

#+name: bare
#+begin_exe
\ex Dogs are barking outside now.
\ex Dogs aren't barking outside now.
#+end_exe

Furthmore, some languages (Russian, Hebrew, etc.) don't typically pronounce the indefinite article at all.

Indefinite noun phrases can be used in predicate position, and conjoined with adjectives:

#+name: pred
#+begin_exe
\ex Lucas is an authority on unicorns.
\ex Lucas is competent in semantics and an authority on unicorns.
#+end_exe

One conclusion that has been drawn on this basis is that the basic denotation of an indefinite noun phrase is type \(E \to T\).

#+name: indef
#+begin_exe
\ex \(\set{x  \in \mathbf{Dom}_E | x \text{ is an authority on unicorns} }\)
#+end_exe

If this is right, then we need existential raising to interpret indefinite noun phrases in argument position, even for English.

#+name: argument
#+begin_exe
\ex An authority on unicorns is teaching this class.
#+end_exe

A similar point can be made for numerals, which can seemingly occur in predicate position:

#+name: numeral
#+begin_exe
\ex Those are two dolphins.
#+end_exe

We can extend an /existential raising/ analysis to numerals in argument position:

#+name: two-dolphins
#+begin_exe
\ex \(\eval{two dolphins} = \set{X \subseteq \mathbf{Dom}_{ET} | X\text{ are dolphins and }\mathbf{card}(X) = 2}_{}\)
#+end_exe

#+name: two
#+begin_exe
\ex Two dolphins are swimming over there.
#+end_exe

Note this means that we can simply treat *two* as an adjectival modifier of collections:

#+name: two
#+begin_exe
\ex \(\eval{two} = \set{X \subseteq \mathbf{Dom}_{ET} | \mathbf{card}(X) = 2}\)
#+end_exe

* Overlap and choice raising

The sets encoded by *doctor* and *lawyer* may overlap but not completely coincide.

#+name: overlap
#+begin_exe
\ex A doctor and lawyer met.
#+end_exe

We can't conclude from this sentence that the two people who met aren't also lawyers and doctors respectively.

Minimization gives rise to a problem. We end up with a set of sets \(S\) with the following properties:

- \(S\) contains a doctor \(d\).
- \(S\) contains a lawyer (who may be identical or distinct from \(d\)).
- \(S\) has no proper subset that contains a lawyer and a doctor.
  
This means that the resulting sets can only either be:

- Singleton sets containing an individual who is both a lawyer and a doctor.
- Pairs of single-profession doctors and lawyers.
  
If the two professions coincide then ([[overlap]]) is predicted to just be deviant for the same reason that "John met" is.

Winter has a similar problem with cases like the following:

#+name: overlap2
#+begin_exe
\ex John and some man met.
#+end_exe



#+print_bibliography:
